name: 'S3 Bucket Website Deploy'
description: 'Will deploy files into S3 Bucket and enable bucket website with given configuration'
author: 'Matthias Prost'
inputs:
  S3_ACCESS_KEY:
    description: 'S3 Key of the project'
    required: true
  S3_SECRET_KEY:
    description: 'S3 Secret Key of the project'
    required: true
  S3_ENDPOINT:
    description: 'Endpoint of your S3 bucket. Ex: s3.fr-par.scw.cloud'
    required: true
  S3_REGION:
    description: 'Region of your S3 bucket. Ex: fr-par'
    required: true
  BUCKET_NAME:
    description: 'Enter a bucket name there. Bucket will be created if not existing.'
    required: true
  WEBSITE_CONFIG_PATH:
    description: 'Root path of the file that contains configuration for bucket website, should be a .json. See example file in repository.'
    required: false
    default: '/s3-default-config-file/.bucket-website.json'
  BUCKET_POLICY_CONFIG_PATH:
    description: 'Root path of the file that contains configuration bucket website policies, should be a .json.tql. See example file in repository'
    required: false
    default: '/s3-default-config-file/.bucket-policy.json.tpl'
  SOURCE_DIRECTORY:
    description: 'Root path of the source folder that will be sync with your bucket.'
    required: false
    default: '.'
  SYNC_ARGS:
    description: 'Arguments you can add to s3 sync.'
    required: false
    default: '--delete'
runs:
  using: docker
  image: Dockerfile
